### ISSUE TITLE
usar neomorphism para diseño del front

### ISSUE THREAD

**Issue by alevilar** [paxapos/tina#10]
investigar si hay algo mejor que esto:
https://demo.themesberg.com/neumorphism-ui/

![image](https://user-images.githubusercontent.com/222193/177612355-f37234d0-2499-4ba9-a98e-71b2190ec51f.png)

**Comment by alevilar** [comment]
https://neumorphism.io/#e0e0e0
para generar botones

**Comment by alevilar** [comment]
https://www.iconfinder.com


para iconos gratis

**Comment by MoscheTom** [comment]
pantalla base de entrenamiento de tina

`<html>
<title>TINA</title>
<style>
.button{
  background-color: #008CBA; 
  border: none;
  border-radius: 4px;
  color: white;
  padding: 15px 42px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 0px 0px;
  cursor: pointer;
  border-radius: 54px;
  background: #0c00ad;
  box-shadow: inset 5px 5px 23px #050045,
            inset -5px -5px 23px #1300ff;
}
.button2 {  
  background-color: #008CBA; 
  border: none;
  border-radius: 4px;
  color: white;
  padding: 15px 42px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 0px 0px;
  cursor: pointer;
  border-radius: 54px;
  background: #ac8211;
  box-shadow: inset 5px 5px 23px #453407,
              inset -5px -5px 23px #ffd01b;
}
.button3 {
  background-color: #008CBA; 
  border: none;
  border-radius: 4px;
  color: white;
  padding: 15px 42px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 0px 0px;
  cursor: pointer;
  border-radius: 54px;
  background: #990000;
  box-shadow: inset -5px 5px 23px #3d0000,
              inset 5px -5px 23px #f50000;
} 
body {
  background-color: lightgreen;
}

</style>
<body>

<h1><center>TINA's training page</center></h1>
<div style="position:absolute;left:150;" class="container">
<form action="">
  <label for="fname">number of photos:</label><br>
  <input type="text" id="fname" name="fname" value="">
  </div>
  <div style="position:absolute;left:400;" class="container">
  <label for="food">cooking time:</label><br>
  <select id="food" name="food">
    <option value="1 min">1 min</option>
    <option value="5 min">5 min</option>
    <option value="10 min">10 min</option>
    <option value="15 min">15 min</option>
  </select>
  </div>
  <br>
  <button class="button" style="position:absolute;right:700;">Capture</button>
  <button class="button button2" style="position:absolute;right:450;">Delete</button>
</form>
<br>
<br>
<br>
<br>
<br>
<br>
<div style="position:absolute;left:150;" class="container">
	<label for="food">Choose a food:</label><br>
  <select id="food" name="food">
    <option value="ravioli">Ravioli</option>
    <option value="spaguetti">Spaguetti</option>
    <option value="beef">beef</option>
    <option value="sausages">sausages</option>
  </select>
</div>
<form action="/action_page.php">
<div style="position:absolute;left:400;" class="container">
	<label for="food">Status:</label><br>
  <select id="" name="food">
    <option value="raw food">raw food</option>
    <option value="ready">ready</option>
    <option value="burnt">burnt</option>
  </select>
  <button class="button button3" style="position:absolute;left:250;">Send Model</button>
 </div>
</form>
</body>
</html>`

**Comment by MoscheTom** [comment]
<html>
<title>TINA</title>
<style>
.button{
  background-color: #008CBA; 
  border: none;
  border-radius: 4px;
  color: white;
  padding: 15px 42px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 0px 0px;
  cursor: pointer;
  border-radius: 54px;
  background: #0c00ad;
  box-shadow: inset 5px 5px 23px #050045,
            inset -5px -5px 23px #1300ff;
}
.button2 {  
  background-color: #008CBA; 
  border: none;
  border-radius: 4px;
  color: white;
  padding: 15px 42px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 0px 0px;
  cursor: pointer;
  border-radius: 54px;
  background: #ac8211;
  box-shadow: inset 5px 5px 23px #453407,
              inset -5px -5px 23px #ffd01b;
}
.button3 {
  background-color: #008CBA; 
  border: none;
  border-radius: 4px;
  color: white;
  padding: 15px 42px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 0px 0px;
  cursor: pointer;
  border-radius: 54px;
  background: #990000;
  box-shadow: inset -5px 5px 23px #3d0000,
              inset 5px -5px 23px #f50000;
} 
body {
  background-color: lightgreen;
}

</style>
<body>

<h1><center>TINA's training page</center></h1>
<div style="position:absolute;left:150;" class="container">
<form action="">
  <label for="fname">number of photos:</label><br>
  <input type="text" id="fname" name="fname" value="">
  </div>
  <div style="position:absolute;left:400;" class="container">
  <label for="food">cooking time:</label><br>
  <select id="food" name="food">
    <option value="1 min">1 min</option>
    <option value="5 min">5 min</option>
    <option value="10 min">10 min</option>
    <option value="15 min">15 min</option>
  </select>
  </div>
  <br>
  <button class="button" style="position:absolute;right:700;">Capture</button>
  <button class="button button2" style="position:absolute;right:450;">Delete</button>
</form>
<br>
<br>
<br>
<br>
<br>
<br>
<div style="position:absolute;left:150;" class="container">
	<label for="food">Choose a food:</label><br>
  <select id="food" name="food">
    <option value="ravioli">Ravioli</option>
    <option value="spaguetti">Spaguetti</option>
    <option value="beef">beef</option>
    <option value="sausages">sausages</option>
  </select>
</div>
<form action="/action_page.php">
<div style="position:absolute;left:400;" class="container">
	<label for="food">Status:</label><br>
  <select id="" name="food">
    <option value="raw food">raw food</option>
    <option value="ready">ready</option>
    <option value="burnt">burnt</option>
  </select>
  <button class="button button3" style="position:absolute;left:250;">Send Model</button>
 </div>
</form>
</body>
</html>

**Comment by MoscheTom** [comment]
###Pantalla de entrenamiento de Tina (beta)
`<html>
<title>TINA</title>
<style>
.button{
  background-color: #008CBA; 
  border: none;
  border-radius: 4px;
  color: white;
  padding: 15px 42px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 0px 0px;
  cursor: pointer;
  border-radius: 54px;
  background: #0c00ad;
  box-shadow: inset 5px 5px 23px #050045,
            inset -5px -5px 23px #1300ff;
}
.button2 {  
  background-color: #008CBA; 
  border: none;
  border-radius: 4px;
  color: white;
  padding: 15px 42px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 0px 0px;
  cursor: pointer;
  border-radius: 54px;
  background: #ac8211;
  box-shadow: inset 5px 5px 23px #453407,
              inset -5px -5px 23px #ffd01b;
}
.button3 {
  background-color: #008CBA; 
  border: none;
  border-radius: 4px;
  color: white;
  padding: 15px 42px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-size: 16px;
  margin: 0px 0px;
  cursor: pointer;
  border-radius: 54px;
  background: #990000;
  box-shadow: inset -5px 5px 23px #3d0000,
              inset 5px -5px 23px #f50000;
} 
body {
  background-color: lightgreen;
}

</style>
<body>

<h1><center>TINA's training page</center></h1>
<div style="position:absolute;left:150;" class="container">
<form action="">
  <label for="fname">number of photos:</label><br>
  <input type="text" id="fname" name="fname" value="">
  </div>
  <div style="position:absolute;left:400;" class="container">
  <label for="food">cooking time:</label><br>
  <select id="food" name="food">
    <option value="1 min">1 min</option>
    <option value="5 min">5 min</option>
    <option value="10 min">10 min</option>
    <option value="15 min">15 min</option>
  </select>
  </div>
  <br>
  <button class="button" style="position:absolute;right:700;">Capture</button>
  <button class="button button2" style="position:absolute;right:450;">Delete</button>
</form>
<br>
<br>
<br>
<br>
<br>
<br>
<div style="position:absolute;left:150;" class="container">
	<label for="food">Choose a food:</label><br>
  <select id="food" name="food">
    <option value="ravioli">Ravioli</option>
    <option value="spaguetti">Spaguetti</option>
    <option value="beef">beef</option>
    <option value="sausages">sausages</option>
  </select>
</div>
<form action="/action_page.php">
<div style="position:absolute;left:400;" class="container">
	<label for="food">Status:</label><br>
  <select id="" name="food">
    <option value="raw food">raw food</option>
    <option value="ready">ready</option>
    <option value="burnt">burnt</option>
  </select>
  <button class="button button3" style="position:absolute;left:250;">Send Model</button>
 </div>
</form>
</body>
</html>`

**Comment by MoscheTom** [comment]
[tina_train_page_code.pdf](https://github.com/paxapos/tina/files/9145252/tina_train_page_code.pdf)

**Comment by sofiokreniec** [comment]
[training_page_figma.pdf](https://github.com/paxapos/tina/files/9176528/training_page_figma.pdf)

**Comment by sofiokreniec** [comment]
[TRAIN PAGE 2.pdf](https://github.com/paxapos/tina/files/9176570/TRAIN.PAGE.2.pdf)

**Comment by alevilar** [comment]
si estan usando figma pueden compartir el link

no compartan PDF porque no nos sirve para WEB

**Comment by sofiokreniec** [comment]
https://www.figma.com/file/XouI0eEuA4QhCun1WCBGi3/TRAIN-PAGE-1?fuid=1127658563741621196

**Comment by alevilar** [comment]
fijate si podes hacerlo publico (seria lo ideal) o compartilo con mi mai
***@***.*** asi lo puedo ver

**Comment by alevilar** [comment]
Consulta:

el boton 2 para que sirve?

![image](https://user-images.githubusercontent.com/222193/182184096-51481d2a-0bfe-40cf-b3f5-683d16f4803d.png)


por otro lado. es mejor crear 2 paginas figma

1.- para la pagina inicial de crga de datos previo a sacar fotos
2 - para la pagina 2 que lista las fotos sacadas, donde se seleccionaran y se guardaran las fotos


por esta razon voy a separar issues en 2, 1 por cada pagina a diseñar.

las issues en cuestion son las:
#18 y la #19 

cierreo esta issue, pero la seguimos en las otras 2
