### ISSUE TITLE
generar 2 comandos x consola, 1 para el predict y otro para el train

### ISSUE THREAD

**Issue by alevilar** [paxapos/tina#15]
train asi:

- [x] python manage.py ia train {NOMBRE_PRODUCTO}

Ejemplo: python manage.py ia train Milanesas

predecir asi:

- [x] python manage.py ia predict {NOMBRE_PRODUCTO} {PATH_IMAGEN}

python manage.py ia predict /hasioasi.jpg

**Comment by joaaquinhidalgo** [comment]
para poder probar los comandos y todo el proyecto en general, debería tener linux y hacerlo desde la consola?

**Comment by spetrungaro** [comment]
No hace falta Linux, se puede hacer desde la terminal de Windows (cmd o powershell). Igualmente el proyecto entero no va a funcionar si no es en una Raspberry Pi. Estoy trabajando para sacar el codigo exclusivo para Raspberry y que se pueda correr en todos lados. Si queres ejecutar un modulo (archivo) de python lo podes hacer mediante line de comandos haciendo por ejemplo `python ia_engine.py` dirigiendote previamente al directorio donde esta ese archivo

**Comment by spetrungaro** [comment]
Linux:
![image](https://user-images.githubusercontent.com/7402298/179848635-87320299-68cf-44e8-ae83-0627b613a1a4.png)

Windows:
![image](https://user-images.githubusercontent.com/7402298/179848954-3c0a0ccc-4070-408a-b8f9-b55f8c0686de.png)

**Comment by joaaquinhidalgo** [comment]
encontré una página donde dice una forma de crear comandos con la libreria click (https://pywombat.com/articles/CLI-python).
sirve para lo que estamos haciendo ahora o es de algo distinto?

**Comment by spetrungaro** [comment]
Si queres agregar argumentos antes de la ejecucion de un archivo de python, podes hacerlo sin ninguna libreria extra. Podes usar una que ya viene y se llama `argparse` https://docs.python.org/3/library/argparse.html

La documentacion es larga pero es poco lo que se necesita, argparse es en la que se basan para hacer el que mandaste vos. Si te fijas en el proyecto nuestro de "fiscalberry" el archivo `server.py` lo tiene implementado abajo de todo:

https://github.com/paxapos/fiscalberry/blob/fiscalberry3-EscP/server.py

Podes darle tu implementacion y cuando subas el codigo en una pull request te lo revisamos y ahi voy a poder marcarte como se podria mejorar. Pero con ese alcanza y sobra. Si es importante que hagas lo de `if __name__ == '__main__'` y ahi adentro pongas este codigo, para que solo se ejecute eso cuando corres el archivo directamente y no cuando lo llamemos desde otro archivo de python

**Comment by joaaquinhidalgo** [comment]
no entiendo a que te referís con lo de  if __name__ == '__main__'  pero ahora voy a leer la documentación que me pasaste y si la duda persiste te vuelvo a escribir, gracias

**Comment by spetrungaro** [comment]
En python se usa 
```
if __name__ == '__main__':
    codigo a ejecutar
```
para colocar codigo dentro de la condicion if  que se va a ejecutar solo cuando el archivo se corre de manera directa. Y no por ejemplo, cuando lo importas como libreria dentro de otro archivo de python.

Si ves el ejemplo del archivo que te pase (server.py) primero se definen todas las funciones, clases, lo que necesites. Abajo de todo se pone esa condicion y dentro de la misma pondrias, por ejemplo, que se ejecute la funcion "train" o "predict":

if __name__ == '__main__':
    train()
    predict()

Adentro le metes el codigo que vos quieras que se ejecute cuando lo corres. Pero la condicion permite que si yo lo uso desde otro archivo de python no me lo ejecute si o si, porque yo lo que haria seria importarlo para llamar a las funciones cuando yo tenga ganas dentro de mi codigo.

Con el argparser podes hacerte 2 argumentos, uno que sea --train y otro --predict y anidas otra condicion que haga que se ejecute uno u otro dependiendo de que argumento usaste:

```
if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Entrena o predice modelos')
	parser.add_argument('--train', 
							help='Entrenar', 
							action='store_true')
	parser.add_argument('--predict', 
							help='Iniciar como servidor SocketIO', 
							action='store_true')
	args = parser.parse_args()

	if args.train:
		train()
	elif args.predict:
               predict()
```

Aca si yo ejecuto el archivo en consola haciendo:
`python ia_engine.py --train`
estaria ejecutando solo la funcion train porque asi le puse en el argumento.

Esta es una version simplificada, porque al lado de --train podes poner un directorio y que el argr¿parser lo tome y asi lo ingresas en el código, etc.

**Comment by alevilar** [comment]
lo que te pasa santi esta buenisimo que lo sepas manejar, porque es a a nivel de python y te va a servir. 

pero puntualmente lo que me interesa es que puedas ejecutar el comando desde django

para ello tenes que leer esta docu

https://docs.djangoproject.com/es/4.0/howto/custom-management-commands/

y ver en _tina/ia/management/commands/_ que tenes un archivo llamado **_ia.py_**


por eso es que desde consola, tanto en windows como en linux, podrias llamar a:

python manage.py ia train Milanesas

te explico comando por comando:;

**python** es el comando para ejecutar python
**manage.py** es el comando para ejecutar django
**ia** es el comando para ejecutar tina/ia/management/commands/ia.py
**train** es el argumento que tenes que aprender a leer en tina/ia/management/commands/ia.py cuya documentacin te paso arriba para que leas y aprendas a pasar argumentos

**Milanesas** es otro parametro (o argumento) que le pasas al script que estamos armando en tina/ia/management/commands/ia.py

**Comment by joaaquinhidalgo** [comment]
si, ya vi como llamar a un archivo desde la consola, ahora voy a leer lo que me pasaste ale y voy comentando

**Comment by joaaquinhidalgo** [comment]
estuve leyendo la documentación y viendo el código, no entiendo que hacen las siguientes líneas

<<<<<<< HEAD:ia/management/commands/ia.py
        engine.train("Milanesas")
        prediction = engine.predict('C:/Users/fabbr/Tina/tina/training/pics/training/burned/pic_01.jpg')
=======
        engine.training_()
        prediction = engine.predict('Test_Pic')
>>>>>>> 616e66f396dd8aeae856acec5634944d7674bc2c:ia/management/commands/train.py

**Comment by alevilar** [comment]
ese codigo quedo mal subdo del git MERGE
la semana pasada cuando subi lo que hice en la reunion, avise que estaba
quedando eso "roto" para que lo arreglen


<<<<<<< HEAD:ia/management/commands/ia.py

por lo tanto no hacen nada. hay que sacarlas

**Comment by joaaquinhidalgo** [comment]
![imagen_2022-07-24_171938556](https://user-images.githubusercontent.com/103291969/180664299-25e07d44-6797-4fa2-9a62-15ac59371ac8.png)
Creo que pude hacer el comando del predict pero me aparece un error que no se como solucionar y tampoco estoy pudiendo probar si funciona (por eso lo paso por acá sin cambiarlo en otro lado)

**Comment by alevilar** [comment]
asigne a @tomasfabbrini  para que te de una mano. ya que dependemos de esto para poder probar el real funcionamiento de la red neuronal. 

a simple vista no logro ver el error, proba quitando esa linea a ver que pasa. de todos modos no lo vi en profundidad aun

**Comment by spetrungaro** [comment]
Esta mal la linea 12 al final que dice type=image:str. Tiene que ser type=str

**Comment by joaaquinhidalgo** [comment]
corrigiendo la linea 12 ya no hay problemas en el código cuando lo pruebo pero me aparece problema por los import

![image](https://user-images.githubusercontent.com/103291969/181277186-08c092ce-316a-48f1-b7f9-172fd2e3310b.png)

**Comment by alevilar** [comment]
probaste googleando el problema ese que aparece ahi en consola?

**Comment by joaaquinhidalgo** [comment]
lo estuve buscando y todavia no lo pude solucionar

**Comment by tomasfabbrini** [comment]
Ya funcionan los dos comandos, el predict devuelve bien los valores pero después tira un error que no supe solucionar y no sé hasta que punto afecta al programa. Probando el predict directamente dentro del código devuelve el mismo valor que por consola pero sin el error

**Comment by alevilar** [comment]
ok, copia el error que aparece en una issue. asi queda pendiente para
resolver

**Comment by joaaquinhidalgo** [comment]
runserver : El término 'runserver' no se reconoce como nombre de un cmdlet, función, archivo de script o programa ejecutable. Compruebe si escribió correctamente el nombre o, si incluyó una ruta de acceso, compruebe que 
dicha ruta es correcta e inténtelo de nuevo.
En línea: 1 Carácter: 1
+ runserver
+ ~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (runserver:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by joaaquinhidalgo** [comment]
puse el visual studio code runserver cuando abrí el proyecto pero me sale ese error

**Comment by joaaquinhidalgo** [comment]
ya pude solucionarlo y pude ejecutar runserver, ahora me sale este error
![image](https://user-images.githubusercontent.com/103291969/182410229-d6ae5fb8-532c-4a0b-961b-3a4c88d8cdb2.png)

**Comment by alevilar** [comment]
proba, en otra carpeta, de armarte un proyecto de CERO e instalarte DJANGO

https://docs.djangoproject.com/en/4.0/topics/install/

instalate primero django, tal como si harias un nuevo proyecto. y fijate si
logras que te funciona siguiendo esos pasos

**Comment by joaaquinhidalgo** [comment]
estuve siguiendo los pasos de la página y tengo este error en la carpeta que cree como prueba, creo que pude instalar DJANGO pero cuando ejecuto runserver en tina me sigue apareciendo el mismo error
![image](https://user-images.githubusercontent.com/103291969/182453596-c9f2ef69-5dba-42f6-a881-5156c56debc8.png)

**Comment by alevilar** [comment]
si miras el lionk a la docu que te pase arriba, no estas realizando los pasos correctos para instalar django. la documentacion oficial esta en ingles. pero si buscas por otro lado (google), o en youtube podras encontrar que expliquen en castellano como hacerlo
