### ISSUE TITLE
crear en figma la pagina principal de entrenamiento 

### ISSUE THREAD

**Issue by alevilar** [paxapos/tina#18]
la pagina 1 contiene el boton para sacar foto
el input con cantidad de fotos a sacar
y el input con el delay que tendra para sacar cada foto

**Comment by sofiokreniec** [comment]
https://www.figma.com/file/4ysBv2hJRhGDJdV0aU7Ic4/TRAINING-PAGE?node-id=0%3A1

**Comment by sofiokreniec** [comment]
https://www.figma.com/file/4ysBv2hJRhGDJdV0aU7Ic4/TRAINING-PAGE?node-id=0%3A1

**Comment by MoscheTom** [comment]
codigo de la pantalla 1 de Tina hasta ahora
`<html>
<head><meta name="viewport" content="width=device-width, initial-scale=1.0"></head>
<style>

body {
background: linear-gradient(180deg, #353A40 0%, #16171B 100%);
border-radius: 60px;
}
.rectangulo{
position: absolute;
width: 1024px;
height: 155px;
left: calc(50% - 1024px/2);
top: 387px;

background: #242424;
box-shadow: 20px 20px 20px #1A1818, inset 5px 5px 20px #1A1818;
border-radius: 10px;
}
.cuadrado{

background: #242424;
box-shadow: 20px 20px 20px #1A1818, inset 5px 5px 20px #1A1818;
border-radius: 10px;
}
.titulo{

}
.box1{
box-shadow: 20px 20px 50px #00d2c6, 
            -30px -30px 60px #00ffff;
border-radius: 25px;
background: linear-gradient(145deg, #3d3d3d, #494949);
box-shadow:  47px 47px 33px #3a3a3a,
             -47px -47px 33px #4e4e4e;
}

.leftcolumn {   
  float: left;
  width: 20%;
  padding-left: 10px;
  background: linear-gradient(180deg, #353A40 0%, #16171B 100%);
  border-radius: 60px;
  border-radius: 10px;
}


.rightcolumn {
  float: left;
  width: 20%;
  padding-left: 20px;
  background: linear-gradient(180deg, #353A40 0%, #16171B 100%);
  border-radius: 60px;
  border-radius: 10px;
  }
.contenedor{
  background: linear-gradient(180deg, #353A40 0%, #16171B 100%);
  border-radius: 60px;
  border-radius: 10px;
}
</style>

<center><font color="#7B52A3"><h2>PaxaPos-TINA</h2></font></center>
<div class="titulo"><center><font color="white"><h1>TRAINING</h1></font></center></div>
<br>
<br>
<br>
<br>
<br>
<h3><font color="white">First Steps</h3></font>
<p><font color="gray">In the following fields you must insert the number of photos you want to take and the number of seconds in which it will be done</font>
<br>
<br>

<div class="leftcolumn"><font color="white">Amount Pictures </font>
<br>
<input class="contenedor" type="img" id="fname" name="fname" value="">
</div>

<div class="rightcolumn" style= "position: absolute;left:500;"><font color="white">Seconds</font>
<br>
<input class="contenedor"  type="img" id="fname" name="fname" value="">
</div>

<br>
<br>

</html>`

**Comment by MoscheTom** [comment]
imagen desde pc
![image](https://user-images.githubusercontent.com/103292063/186469012-3230b043-a8be-4705-bb4a-ff55d1ef13f4.png)

**Comment by MoscheTom** [comment]
imagen desde movil
![Screenshot_20220824-131550_Drive](https://user-images.githubusercontent.com/103292063/186470231-7175c25d-533f-45f2-ae04-90c482d0d4c9.jpg)

**Comment by sofiokreniec** [comment]
Buenas noches, cuando puedas decime específicamente que necesitas que modifique de los botones y los input porque cumplen con la consigna de usar neomorfismo y  respecto al botón solo le cambie el color y el ícono del modelo que me pasaste.

**Comment by MicaBrizuela** [comment]
https://www.figma.com/file/4ysBv2hJRhGDJdV0aU7Ic4/TRAINING-PAGE?node-id=0%3A1 los cambios se actualizaron según lo establecido anteriormente. El link siempre es el mismo, y los cambios se actualizan automáticamente una vez completados.

**Comment by alevilar** [comment]
quitar el slide up porque no va 
![image](https://user-images.githubusercontent.com/222193/193852310-278f7cfe-acc4-4583-be70-aed366450415.png)

**Comment by sofiokreniec** [comment]
https://www.figma.com/file/4ysBv2hJRhGDJdV0aU7Ic4/TRAINING-PAGE?node-id=0%3A1
