### ISSUE TITLE
crear en figma la pagina que recibe las fotos sacadas (pagina 2)

### ISSUE THREAD

**Issue by alevilar** [paxapos/tina#19]
esta pagina lista las fotos sacadas y provee un mecanismo para seleccionar las fotos que deben ser almacenadas

luego, habra un SELECT input listando los productos disponibles
otro select con los SCORES (puntaje de coccion) del producto seleccionado
y, por ultimo el boton para guardar las fotos en la carpeta y con el punto de coccion seleccionado

**Comment by sofiokreniec** [comment]
https://www.figma.com/file/4ysBv2hJRhGDJdV0aU7Ic4/TRAINING-PAGE?node-id=0%3A1

**Comment by sofiokreniec** [comment]
https://www.figma.com/file/4ysBv2hJRhGDJdV0aU7Ic4/TRAINING-PAGE?node-id=0%3A1

**Comment by alevilar** [comment]
buenisimo esta quedando mucho mejor. pero me gustaria que busquen mejorar
visualmente los INPUTS y la galería de imagenes pongan un par de imagens de
ejemplo.

**Comment by sofiokreniec** [comment]
https://www.figma.com/file/4ysBv2hJRhGDJdV0aU7Ic4/TRAINING-PAGE?node-id=0%3A1
