### ISSUE TITLE
html y css basado en figma

### ISSUE THREAD

**Issue by MoscheTom** [paxapos/tina#22]

**Comment by MoscheTom** [comment]
se actualizo el codigo de la pagina de tina siguiendo como referencia la pagina de figma, y comence a crear la segunda pagina

**Comment by alevilar** [comment]
no comiences con la segunda pagina, hasta tanto no tengas bien terminada la primera

yo lo veo asi:

![image](https://user-images.githubusercontent.com/222193/195587874-451be2bd-57a7-499b-a26f-5bae925eef41.png)

y el que tenes que hacer es asi:

![image](https://user-images.githubusercontent.com/222193/195588095-42873101-542a-4a3d-99b2-c0a9ec2718d6.png)

**Comment by alevilar** [comment]
las imagenes las sacas de figma tambien. por ejemplo la camara de fotos la tenes que exportar en formatio SVG (es un formato vectorial que no pierde resolucion)- y la usas en tu proyecto. no tenes que usar otra imagen.

te paso los pasos como hacer eso

1. seleccionas la imagen
2.  vas a exportar
3. seleccionas el formato SVG
4. la descargas
![image](https://user-images.githubusercontent.com/222193/195589912-d10a6d0f-7d45-43ea-99bd-778b6848b42e.png)

**Comment by alevilar** [comment]
los nombres de los archivos los subiste mal . se llamaban **"tina - copia.html"** y no pueden tener espacion en blanco los nombres de los archivos cuando se trata de un proyecto de desarrollo

**Comment by alevilar** [comment]
acabo de subir una nueva version con cambios basados en FIGMA para que vean como podria quedar. hay que seguir los CSS que tienene n figma y copiar de ahi directamente para que quede lo mas parecido posible

**Comment by MoscheTom** [comment]
![image](https://user-images.githubusercontent.com/103292063/199532159-27d630c0-99b9-4e70-a83e-0bc9a051d4bf.png)

**Comment by sofiokreniec** [comment]
![image](https://user-images.githubusercontent.com/103291947/202224051-2b091e1e-6822-4b89-b454-87a329a2455a.png)

La pagina principal se ve asi, esta hosteada y en celular el texto de First steps se ve alineado, si queres te paso el codigo y capaz sabes como alinearlo tanto en computadora como en celular

**Comment by sofiokreniec** [comment]
![image](https://user-images.githubusercontent.com/103291947/202225110-41136d36-8c4d-41da-80d5-42cc138203e8.png)

la de las fotos se ve asi, falta cargarle fotos pero ya se entiende que se muestran bien

**Comment by sofiokreniec** [comment]
![image](https://user-images.githubusercontent.com/103291947/202225310-99f6a7b8-f026-46aa-80bf-5fc4eabc43ad.png)

a esto falta alinear el boton al centro y ponerle la imagen que eso lo hacemos hoy y creo que ya estaría

**Comment by sofiokreniec** [comment]
despues entrar en detalles para que los botones y el input que desliza queden igual al del figma, podemos hacer todo menos lo del tema del input que desliza, no puedo hacer que el progreso se ponga de color violeta, solo pudimos darle formato al track total

**Comment by MoscheTom** [comment]
tampoco sabemos como podemos realizar el select all que esta sobre el cuadro de las fotos en el figma

![image](https://user-images.githubusercontent.com/103292063/202243229-46e1ba04-843f-4282-b4b3-ffa2062e1819.png)

**Comment by alevilar** [comment]
> ![image](https://user-images.githubusercontent.com/103291947/202224051-2b091e1e-6822-4b89-b454-87a329a2455a.png)
> 
> La pagina principal se ve asi, esta hosteada y en celular el texto de First steps se ve alineado, si queres te paso el codigo y capaz sabes como alinearlo tanto en computadora como en celular

![image](https://user-images.githubusercontent.com/222193/203602325-58e14eb2-72c4-431a-b1f8-4f9f211d91dc.png)
