### ISSUE TITLE
crear juego de imagenes para entrenamiento

### ISSUE THREAD

**Issue by alevilar** [paxapos/tina#9]
las imagenes deberian ser simples, para poder comenzar entrenando al algoritmo y hacer pruebas con imagenes que deberian funcionar rapidamente

seria algo asi:

donde el amarillo estaria crudo y el naranja cocido. se podrian armar imagenes en distintos grados de coccion y colocando en la carpeta correspondiente

Adjunto el SVG de Inkscape para hacer mas imagenes
![ountos coccion simplificados](https://user-images.githubusercontent.com/222193/174093609-7415c6cc-ae45-4aba-b38e-cb63019613db.svg)

el juego de imagenes debera estar contenido en un ZIP con un monton de imagenes con esta estcurtcura de carpetas

**{PRODUCT_ALIAS}/{SCORE_NUMBER}/pic_{NUMBER}.jpeg**

estas imagenes no hayq ue subirlas github como parte del proyecto, sino que hay que dejar el ZIP en esta issue como ANEXO. y despues lo agregaremos en la wiki

**Comment by tomasfabbrini** [comment]
[Milanesas.zip](https://github.com/paxapos/tina/files/8983771/Milanesas.zip)

**Comment by alevilar** [comment]
@tomasfabbrini sabes que no logro notar diferencia entre 
entre el 7 y el 8 muy poca
y entre el 7 y el 9 no la notan mis ojos

de todos modos si le tenes fe la probamos asi.... y venmos si la IA lo detecta. el 9 lo haria bien tostadito .. mas  oscuro

**Comment by tomasfabbrini** [comment]
Tuve que cambiarle el tamaño a las imágenes para que la IA las procese más rápido y de paso separé las de entrenamiento de las de validación. Esta es la nueva carpeta

[Milanesas.zip](https://github.com/paxapos/tina/files/9229521/Milanesas.zip)

**Comment by tomasfabbrini** [comment]
[Milanesas.zip](https://github.com/paxapos/tina/files/9480339/Milanesas.zip)

Imágenes achicadas para acelerar el entrenamiento.
